/*==============================================================*/
/* DBMS name:      ORACLE Version 10g                           */
/* Created on:     2015/7/8 15:42:12                            */
/*==============================================================*/


drop table GEN_SCHEME cascade constraints;

drop table GEN_TABLE cascade constraints;

drop table GEN_TABLE_COLUMN cascade constraints;

drop table GEN_TEMPLATE cascade constraints;

drop table SYS_AREA cascade constraints;

drop table SYS_DICT cascade constraints;

drop table SYS_LOG cascade constraints;

drop table SYS_MENU cascade constraints;

drop table SYS_ROLE cascade constraints;

drop table SYS_ROLE_MENU cascade constraints;

drop table SYS_USER cascade constraints;

drop table SYS_USER_ROLE cascade constraints;

/*==============================================================*/
/* Table: GEN_SCHEME                                            */
/*==============================================================*/
create table GEN_SCHEME  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	NAME VARCHAR2(200 CHAR), 
	CATEGORY CLOB, 
	PACKAGE_NAME VARCHAR2(500 CHAR), 
	MODULE_NAME VARCHAR2(30 CHAR), 
	SUB_MODULE_NAME VARCHAR2(30 CHAR), 
	FUNCTION_NAME VARCHAR2(500 CHAR), 
	FUNCTION_NAME_SIMPLE VARCHAR2(100 CHAR), 
	FUNCTION_AUTHOR VARCHAR2(100 CHAR), 
	GEN_TABLE_ID VARCHAR2(200 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR), 
	CREATE_DATE DATE, 
	UPDATE_BY VARCHAR2(64 CHAR), 
	UPDATE_DATE DATE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN GEN_SCHEME.ID IS 'ID';
 
   COMMENT ON COLUMN GEN_SCHEME.NAME IS 'NAME';
 
   COMMENT ON COLUMN GEN_SCHEME.CATEGORY IS 'CATEGORY';
 
   COMMENT ON COLUMN GEN_SCHEME.PACKAGE_NAME IS 'PACKAGE_NAME';
 
   COMMENT ON COLUMN GEN_SCHEME.MODULE_NAME IS 'MODULE_NAME';
 
   COMMENT ON COLUMN GEN_SCHEME.SUB_MODULE_NAME IS 'SUB_MODULE_NAME';
 
   COMMENT ON COLUMN GEN_SCHEME.FUNCTION_NAME IS 'FUNCTION_NAME';
 
   COMMENT ON COLUMN GEN_SCHEME.FUNCTION_NAME_SIMPLE IS 'FUNCTION_NAME_SIMPLE';
 
   COMMENT ON COLUMN GEN_SCHEME.FUNCTION_AUTHOR IS 'FUNCTION_AUTHOR';
 
   COMMENT ON COLUMN GEN_SCHEME.GEN_TABLE_ID IS 'GEN_TABLE_ID';
 
   COMMENT ON COLUMN GEN_SCHEME.CREATE_BY IS 'CREATE_BY';
 
   COMMENT ON COLUMN GEN_SCHEME.CREATE_DATE IS 'CREATE_DATE';
 
   COMMENT ON COLUMN GEN_SCHEME.UPDATE_BY IS 'UPDATE_BY';
 
   COMMENT ON COLUMN GEN_SCHEME.UPDATE_DATE IS 'UPDATE_DATE';
 
   COMMENT ON COLUMN GEN_SCHEME.REMARKS IS 'REMARKS';
 
   COMMENT ON COLUMN GEN_SCHEME.DEL_FLAG IS 'DEL_FLAG';
 
   COMMENT ON TABLE GEN_SCHEME  IS 'GEN_SCHEME';

/*==============================================================*/
/* Table: GEN_TABLE                                             */
/*==============================================================*/
create table GEN_TABLE  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	NAME VARCHAR2(200 CHAR), 
	COMMENTS VARCHAR2(500 CHAR), 
	CLASS_NAME VARCHAR2(100 CHAR), 
	PARENT_TABLE VARCHAR2(200 CHAR), 
	PARENT_TABLE_FK VARCHAR2(100 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR), 
	CREATE_DATE DATE, 
	UPDATE_BY VARCHAR2(64 CHAR), 
	UPDATE_DATE DATE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN GEN_TABLE.ID IS 'ID';
 
   COMMENT ON COLUMN GEN_TABLE.NAME IS 'NAME';
 
   COMMENT ON COLUMN GEN_TABLE.COMMENTS IS 'COMMENTS';
 
   COMMENT ON COLUMN GEN_TABLE.CLASS_NAME IS 'CLASS_NAME';
 
   COMMENT ON COLUMN GEN_TABLE.PARENT_TABLE IS 'PARENT_TABLE';
 
   COMMENT ON COLUMN GEN_TABLE.PARENT_TABLE_FK IS 'PARENT_TABLE_FK';
 
   COMMENT ON COLUMN GEN_TABLE.CREATE_BY IS 'CREATE_BY';
 
   COMMENT ON COLUMN GEN_TABLE.CREATE_DATE IS 'CREATE_DATE';
 
   COMMENT ON COLUMN GEN_TABLE.UPDATE_BY IS 'UPDATE_BY';
 
   COMMENT ON COLUMN GEN_TABLE.UPDATE_DATE IS 'UPDATE_DATE';
 
   COMMENT ON COLUMN GEN_TABLE.REMARKS IS 'REMARKS';
 
   COMMENT ON COLUMN GEN_TABLE.DEL_FLAG IS 'DEL_FLAG';
 
   COMMENT ON TABLE GEN_TABLE  IS 'GEN_TABLE';

/*==============================================================*/
/* Table: GEN_TABLE_COLUMN                                      */
/*==============================================================*/
create table GEN_TABLE_COLUMN  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	GEN_TABLE_ID VARCHAR2(64 CHAR), 
	NAME VARCHAR2(200 CHAR), 
	COMMENTS VARCHAR2(500 CHAR), 
	JDBC_TYPE VARCHAR2(100 CHAR), 
	JAVA_TYPE VARCHAR2(500 CHAR), 
	JAVA_FIELD VARCHAR2(200 CHAR), 
	IS_PK CHAR(1 CHAR), 
	IS_NULL CHAR(1 CHAR), 
	IS_INSERT CHAR(1 CHAR), 
	IS_EDIT CHAR(1 CHAR), 
	IS_LIST CHAR(1 CHAR), 
	IS_QUERY CHAR(1 CHAR), 
	QUERY_TYPE VARCHAR2(200 CHAR), 
	SHOW_TYPE VARCHAR2(200 CHAR), 
	DICT_TYPE VARCHAR2(200 CHAR), 
	SETTINGS CLOB, 
	SORT NUMBER(38,2), 
	CREATE_BY VARCHAR2(64 CHAR), 
	CREATE_DATE DATE, 
	UPDATE_BY VARCHAR2(64 CHAR), 
	UPDATE_DATE DATE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN GEN_TABLE_COLUMN.ID IS 'ID';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.GEN_TABLE_ID IS 'GEN_TABLE_ID';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.NAME IS 'NAME';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.COMMENTS IS 'COMMENTS';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.JDBC_TYPE IS 'JDBC_TYPE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.JAVA_TYPE IS 'JAVA_TYPE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.JAVA_FIELD IS 'JAVA_FIELD';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_PK IS 'IS_PK';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_NULL IS 'IS_NULL';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_INSERT IS 'IS_INSERT';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_EDIT IS 'IS_EDIT';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_LIST IS 'IS_LIST';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.IS_QUERY IS 'IS_QUERY';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.QUERY_TYPE IS 'QUERY_TYPE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.SHOW_TYPE IS 'SHOW_TYPE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.DICT_TYPE IS 'DICT_TYPE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.SETTINGS IS 'SETTINGS';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.SORT IS 'SORT';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.CREATE_BY IS 'CREATE_BY';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.CREATE_DATE IS 'CREATE_DATE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.UPDATE_BY IS 'UPDATE_BY';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.UPDATE_DATE IS 'UPDATE_DATE';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.REMARKS IS 'REMARKS';
 
   COMMENT ON COLUMN GEN_TABLE_COLUMN.DEL_FLAG IS 'DEL_FLAG';
 
   COMMENT ON TABLE GEN_TABLE_COLUMN  IS 'GEN_TABLE_COLUMN';

/*==============================================================*/
/* Table: GEN_TEMPLATE                                          */
/*==============================================================*/
create table GEN_TEMPLATE  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	NAME VARCHAR2(200 CHAR), 
	CATEGORY CLOB, 
	FILE_PATH VARCHAR2(500 CHAR), 
	FILE_NAME VARCHAR2(200 CHAR), 
	CONTENT CLOB, 
	CREATE_BY VARCHAR2(64 CHAR), 
	CREATE_DATE DATE, 
	UPDATE_BY VARCHAR2(64 CHAR), 
	UPDATE_DATE DATE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN GEN_TEMPLATE.ID IS 'ID';
 
   COMMENT ON COLUMN GEN_TEMPLATE.NAME IS 'NAME';
 
   COMMENT ON COLUMN GEN_TEMPLATE.CATEGORY IS 'CATEGORY';
 
   COMMENT ON COLUMN GEN_TEMPLATE.FILE_PATH IS 'FILE_PATH';
 
   COMMENT ON COLUMN GEN_TEMPLATE.FILE_NAME IS 'FILE_NAME';
 
   COMMENT ON COLUMN GEN_TEMPLATE.CONTENT IS 'CONTENT';
 
   COMMENT ON COLUMN GEN_TEMPLATE.CREATE_BY IS 'CREATE_BY';
 
   COMMENT ON COLUMN GEN_TEMPLATE.CREATE_DATE IS 'CREATE_DATE';
 
   COMMENT ON COLUMN GEN_TEMPLATE.UPDATE_BY IS 'UPDATE_BY';
 
   COMMENT ON COLUMN GEN_TEMPLATE.UPDATE_DATE IS 'UPDATE_DATE';
 
   COMMENT ON COLUMN GEN_TEMPLATE.REMARKS IS 'REMARKS';
 
   COMMENT ON COLUMN GEN_TEMPLATE.DEL_FLAG IS 'DEL_FLAG';
 
   COMMENT ON TABLE GEN_TEMPLATE  IS 'GEN_TEMPLATE';

/*==============================================================*/
/* Table: SYS_AREA                                              */
/*==============================================================*/
create table SYS_AREA  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	PARENT_ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	PARENT_IDS CLOB NOT NULL ENABLE, 
	NAME VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	SORT NUMBER(38,0) NOT NULL ENABLE, 
	CODE VARCHAR2(100 CHAR), 
	TYPE CHAR(1 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	CREATE_DATE DATE NOT NULL ENABLE, 
	UPDATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN SYS_AREA.ID IS 'ID';
 
   COMMENT ON COLUMN SYS_AREA.PARENT_ID IS '父节点ID';
 
   COMMENT ON COLUMN SYS_AREA.PARENT_IDS IS '父节点IDS';
 
   COMMENT ON COLUMN SYS_AREA.NAME IS '名称';
 
   COMMENT ON COLUMN SYS_AREA.SORT IS '序号';
 
   COMMENT ON COLUMN SYS_AREA.CODE IS '代码';
 
   COMMENT ON COLUMN SYS_AREA.TYPE IS '类型';
 
   COMMENT ON COLUMN SYS_AREA.CREATE_BY IS '创建者';
 
   COMMENT ON COLUMN SYS_AREA.CREATE_DATE IS '创建日期';
 
   COMMENT ON COLUMN SYS_AREA.UPDATE_BY IS '更新者';
 
   COMMENT ON COLUMN SYS_AREA.UPDATE_DATE IS '更新日期';
 
   COMMENT ON COLUMN SYS_AREA.REMARKS IS '备注';
 
   COMMENT ON COLUMN SYS_AREA.DEL_FLAG IS '删除标记';
 
   COMMENT ON TABLE SYS_AREA  IS '行政区划';
   
/*==============================================================*/
/* Table: SYS_DICT                                              */
/*==============================================================*/
create table SYS_DICT  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	VALUE VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	LABEL VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	TYPE VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	SORT NUMBER(38,0) NOT NULL ENABLE, 
	PARENT_ID VARCHAR2(64 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	CREATE_DATE DATE NOT NULL ENABLE, 
	UPDATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN SYS_DICT.ID IS 'ID';
 
   COMMENT ON COLUMN SYS_DICT.VALUE IS '值';
 
   COMMENT ON COLUMN SYS_DICT.LABEL IS '标签';
 
   COMMENT ON COLUMN SYS_DICT.TYPE IS '类型';
 
   COMMENT ON COLUMN SYS_DICT.DESCRIPTION IS '描述';
 
   COMMENT ON COLUMN SYS_DICT.SORT IS '序号';
 
   COMMENT ON COLUMN SYS_DICT.PARENT_ID IS '父节点ID';
 
   COMMENT ON COLUMN SYS_DICT.CREATE_BY IS '创建者';
 
   COMMENT ON COLUMN SYS_DICT.CREATE_DATE IS '创建日期';
 
   COMMENT ON COLUMN SYS_DICT.UPDATE_BY IS '更新者';
 
   COMMENT ON COLUMN SYS_DICT.UPDATE_DATE IS '更新日期';
 
   COMMENT ON COLUMN SYS_DICT.REMARKS IS '备注';
 
   COMMENT ON COLUMN SYS_DICT.DEL_FLAG IS '删除标记';
 
   COMMENT ON TABLE SYS_DICT  IS '数据字典';

/*==============================================================*/
/* Table: SYS_LOG                                               */
/*==============================================================*/
create table SYS_LOG  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	TYPE CHAR(1 CHAR), 
	TITLE VARCHAR2(255 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR), 
	CREATE_DATE DATE, 
	REMOTE_ADDR VARCHAR2(255 CHAR), 
	USER_AGENT VARCHAR2(255 CHAR), 
	REQUEST_URI VARCHAR2(255 CHAR), 
	METHOD VARCHAR2(5 CHAR), 
	PARAMS CLOB, 
	EXCEPTION CLOB
);

   COMMENT ON COLUMN SYS_LOG.ID IS 'ID';
 
   COMMENT ON COLUMN SYS_LOG.TYPE IS '类型';
 
   COMMENT ON COLUMN SYS_LOG.TITLE IS '标题';
 
   COMMENT ON COLUMN SYS_LOG.CREATE_BY IS '创建者';
 
   COMMENT ON COLUMN SYS_LOG.CREATE_DATE IS '创建日期';
 
   COMMENT ON COLUMN SYS_LOG.REMOTE_ADDR IS '地址';
 
   COMMENT ON COLUMN SYS_LOG.USER_AGENT IS '用户带来';
 
   COMMENT ON COLUMN SYS_LOG.REQUEST_URI IS '请求URI';
 
   COMMENT ON COLUMN SYS_LOG.METHOD IS '方法';
 
   COMMENT ON COLUMN SYS_LOG.PARAMS IS '参数';
 
   COMMENT ON COLUMN SYS_LOG.EXCEPTION IS '异常';
 
   COMMENT ON TABLE SYS_LOG  IS '系统日志';

/*==============================================================*/
/* Table: SYS_MENU                                              */
/*==============================================================*/
create table SYS_MENU  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	PARENT_ID VARCHAR2(64 CHAR), 
	PARENT_IDS CLOB, 
	NAME VARCHAR2(100 CHAR), 
	SORT NUMBER(38,0), 
	HREF CLOB, 
	TARGET VARCHAR2(20 CHAR), 
	ICON VARCHAR2(100 CHAR), 
	IS_SHOW CHAR(1 CHAR), 
	PERMISSION VARCHAR2(200 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR), 
	CREATE_DATE DATE, 
	UPDATE_BY VARCHAR2(64 CHAR), 
	UPDATE_DATE DATE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR), 
	 CONSTRAINT AK_KEY_1_SYS_MENU UNIQUE (ID)
);

   COMMENT ON COLUMN SYS_MENU.ID IS 'ID';
 
   COMMENT ON COLUMN SYS_MENU.PARENT_ID IS '父菜单ID';
 
   COMMENT ON COLUMN SYS_MENU.PARENT_IDS IS '父菜单ids';
 
   COMMENT ON COLUMN SYS_MENU.NAME IS '菜单名称';
 
   COMMENT ON COLUMN SYS_MENU.SORT IS '序号';
 
   COMMENT ON COLUMN SYS_MENU.HREF IS '地址';
 
   COMMENT ON COLUMN SYS_MENU.TARGET IS '目标';
 
   COMMENT ON COLUMN SYS_MENU.ICON IS '图标';
 
   COMMENT ON COLUMN SYS_MENU.IS_SHOW IS '是否可见';
 
   COMMENT ON COLUMN SYS_MENU.PERMISSION IS '权限许可';
 
   COMMENT ON COLUMN SYS_MENU.CREATE_BY IS '创建者';
 
   COMMENT ON COLUMN SYS_MENU.CREATE_DATE IS '创建时间';
 
   COMMENT ON COLUMN SYS_MENU.UPDATE_BY IS '修改者';
 
   COMMENT ON COLUMN SYS_MENU.UPDATE_DATE IS '修改时间';
 
   COMMENT ON COLUMN SYS_MENU.REMARKS IS '描述';
 
   COMMENT ON COLUMN SYS_MENU.DEL_FLAG IS '删除标记';
 
   COMMENT ON TABLE SYS_MENU  IS '菜单';

/*==============================================================*/
/* Table: SYS_ROLE                                              */
/*==============================================================*/
create table SYS_ROLE  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	NAME VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	ENNAME VARCHAR2(255 CHAR), 
	ROLE_TYPE VARCHAR2(255 CHAR), 
	DATA_SCOPE CHAR(1 CHAR), 
	IS_SYS VARCHAR2(64 CHAR), 
	USEABLE VARCHAR2(64 CHAR), 
	CREATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	CREATE_DATE DATE NOT NULL ENABLE, 
	UPDATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT AK_KEY_1_SYS_ROLE UNIQUE (ID)
);

   COMMENT ON COLUMN SYS_ROLE.ID IS 'ID';
 
   COMMENT ON COLUMN SYS_ROLE.NAME IS '角色名称';
 
   COMMENT ON COLUMN SYS_ROLE.ENNAME IS '英文名称';
 
   COMMENT ON COLUMN SYS_ROLE.ROLE_TYPE IS '角色类别';
 
   COMMENT ON COLUMN SYS_ROLE.DATA_SCOPE IS '数据范围';
 
   COMMENT ON COLUMN SYS_ROLE.IS_SYS IS '是否系统默认';
 
   COMMENT ON COLUMN SYS_ROLE.USEABLE IS '是否可用';
 
   COMMENT ON COLUMN SYS_ROLE.CREATE_BY IS '创建者';
 
   COMMENT ON COLUMN SYS_ROLE.CREATE_DATE IS '创建时间';
 
   COMMENT ON COLUMN SYS_ROLE.UPDATE_BY IS '修改者';
 
   COMMENT ON COLUMN SYS_ROLE.UPDATE_DATE IS '修改时间';
 
   COMMENT ON COLUMN SYS_ROLE.REMARKS IS '描述';
 
   COMMENT ON COLUMN SYS_ROLE.DEL_FLAG IS '删除标记';
 
   COMMENT ON TABLE SYS_ROLE  IS '角色';

/*==============================================================*/
/* Table: SYS_ROLE_MENU                                         */
/*==============================================================*/
create table SYS_ROLE_MENU  (
    "ROLE_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"MENU_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN "USR_SC_CSSM"."SYS_ROLE_MENU"."ROLE_ID" IS '角色ID';
 
   COMMENT ON COLUMN "USR_SC_CSSM"."SYS_ROLE_MENU"."MENU_ID" IS '菜单ID';
 
   COMMENT ON TABLE "USR_SC_CSSM"."SYS_ROLE_MENU"  IS '角色菜单';

/*==============================================================*/
/* Table: SYS_USER                                              */
/*==============================================================*/
create table SYS_USER  (
    ID VARCHAR2(64 CHAR) NOT NULL ENABLE,
	LOGIN_NAME VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	PASSWORD VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	NO VARCHAR2(100 CHAR), 
	NAME VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	EMAIL VARCHAR2(200 CHAR), 
	PHONE VARCHAR2(200 CHAR), 
	MOBILE VARCHAR2(200 CHAR), 
	USER_TYPE CHAR(1 CHAR), 
	PHOTO VARCHAR2(1000 CHAR), 
	LOGIN_IP VARCHAR2(100 CHAR), 
	LOGIN_DATE DATE, 
	LOGIN_FLAG VARCHAR2(64 CHAR), 
	OBJECT_ID  VARCHAR2(64 CHAR),
    OBJECT_DAO  VARCHAR2(200 CHAR),
	CREATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	CREATE_DATE DATE NOT NULL ENABLE, 
	UPDATE_BY VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	REMARKS VARCHAR2(255 CHAR), 
	DEL_FLAG CHAR(1 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT AK_KEY_1_SYS_USER UNIQUE (ID)
);

   COMMENT ON COLUMN SYS_USER.ID IS 'ID';
 
   COMMENT ON COLUMN SYS_USER.LOGIN_NAME IS '账号';
 
   COMMENT ON COLUMN SYS_USER.PASSWORD IS '密码';
 
   COMMENT ON COLUMN SYS_USER.NO IS '工号';
 
   COMMENT ON COLUMN SYS_USER.NAME IS '用户名';
 
   COMMENT ON COLUMN SYS_USER.EMAIL IS '邮箱';
 
   COMMENT ON COLUMN SYS_USER.PHONE IS '电话';
 
   COMMENT ON COLUMN SYS_USER.MOBILE IS '手机';
 
   COMMENT ON COLUMN SYS_USER.USER_TYPE IS '身份';
 
   COMMENT ON COLUMN SYS_USER.PHOTO IS '图像';
 
   COMMENT ON COLUMN SYS_USER.LOGIN_IP IS '上次登录ip';
 
   COMMENT ON COLUMN SYS_USER.LOGIN_DATE IS '上次登录时间';
 
   COMMENT ON COLUMN SYS_USER.LOGIN_FLAG IS '登录标记';
   
   COMMENT ON COLUMN SYS_USER.OBJECT_ID IS '对象id';
   
   COMMENT ON COLUMN SYS_USER.OBJECT_DAO IS '对象dao';
 
   COMMENT ON COLUMN SYS_USER.CREATE_BY IS '创建者';
 
   COMMENT ON COLUMN SYS_USER.CREATE_DATE IS '创建时间';
 
   COMMENT ON COLUMN SYS_USER.UPDATE_BY IS '修改者';
 
   COMMENT ON COLUMN SYS_USER.UPDATE_DATE IS '修改时间';
 
   COMMENT ON COLUMN SYS_USER.REMARKS IS '描述';
 
   COMMENT ON COLUMN SYS_USER.DEL_FLAG IS '删除标记';
 
   COMMENT ON TABLE SYS_USER  IS '用户';

/*==============================================================*/
/* Table: SYS_USER_ROLE                                         */
/*==============================================================*/
create table SYS_USER_ROLE  (
    "USER_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"ROLE_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE
);

   COMMENT ON COLUMN "USR_SC_CSSM"."SYS_USER_ROLE"."USER_ID" IS '用户ID';
 
   COMMENT ON COLUMN "USR_SC_CSSM"."SYS_USER_ROLE"."ROLE_ID" IS '角色ID';
 
   COMMENT ON TABLE "USR_SC_CSSM"."SYS_USER_ROLE"  IS '用户角色';
